version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile # Atau './docker/php/Dockerfile' jika kamu letakkan di folder
    container_name: php_app
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx_web
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

  db:
    image: mariadb:10.5
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: asmpid
      MYSQL_USER: appuser
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - app-network

  node:
    image: node:20-alpine
    container_name: node_app
    working_dir: /usr/src/app
    volumes:
      - ./node-app:/usr/src/app
    command: sh -c "npm install && npm run dev"
    networks:
      - app-network
    depends_on:
      - app

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
